
# Introduction {#intro} 
Estimated time: 15 minutes

This course provides PhD candidates with the essential knowledge and the core skills to manage research data according to best practice. You will be able to integrate good data management practices within your workflow from the beginning of your projects. The application of this knowledge to your research will allow you to reflect on how to work efficiently and in a reproducible manner with your research data, while complying with funders and institutional requirements.

This course contains a lot of self-paced elements. Make sure to plan your time accordingly. You will get most out of this course if you keep an eye on the Discussions with your peers throughout the week. Do you run into any problems in scheduling time? Let us know!

## Relevant dates:  
Course start:    Monday, DD-MM-YYYY  
Course end date: Friday, DD-MM-YYYY  

Class sessions: 

Course load: approximately 4-6 hours per week


## Learning Objectives:
After completing this course, you will be able to:

*	Realize the important role that good data management plays in research

*	Identify different types of research data and recognize the regulations, policies and/or legal requirements associated with them.
*	List the main components of the FAIR data principles and connect them to your own research workflows.
*	Employ the acquired knowledge to design an efficient research data management strategy for your projects according to best practices.

## Code of Conduct
* Everyone is learning, including instructors - please have patience and respect towards each other! 
* Use welcoming and inclusive language when interacting with your peers and instructors
* Be respectful of different viewpoints and experiences
* Provide and gracefully accept constructive criticism

See also the [TU Delft Code of Conduct](https://www.tudelft.nl/en/about-tu-delft/strategy/integrity-policy/tu-delft-code-of-conduct). 

If at any point you're confronted with undesirable behaviour, please reach out to the instructor or the [TU Delft confidential advisors](https://www.tudelft.nl/en/about-tu-delft/strategy/integrity-policy/confidential-advisors).


## Assessment criteria

In order to receive the 1.5 Graduate School Credits you have to:

*	Complete all activities 
  * Interact with all course activities ( topics & quizzes)
  * Participate in all discussions (Q&A are optional)
	* Submit assignments (data flow maps) in weeks 1 and 2 and the assignment of week 3 (reflection on RDM strategy).
	* Write a Data Management Plan using DMPonline
*	Attend and participate in all Class Sessions 

Note: you will not be graded on your assignments. 
Use the class sessions and Discussions to gather feedback.

## Support

You will get most out of this course by interacting with your peers and the instructor. 
You can do this via GitHub issues, where you can also ask questions.   

For all deadlines:
*	see the [Course Schedule](link) 

For other questions please contact Esther. 

## License and attribution

**All the course materials can be found here**:
Martinez-Lavanchy, P.M., van Schöll, Pim, & Zormpa, Eirini. (2022). TU Delft Research Data Management 101 course. Zenodo. doi: [10.5281/zenodo.6325919](https://doi.org/10.5281/zenodo.6325919)

Parts of the content of this course are based on: 
Holmstrand, K.F., den Boer, S.P.A., Vlachos, E., Martínez-Lavanchy, P.M., Hansen, K.K. (Eds.) (2019). Research Data Management (eLearning course). doi: [10.11581/dtu:00000047](https://doi.org/10.11581/dtu:00000047)

This website is made using [Quarto](https://quarto.org/)
Allaire, J., Teague, C., Scheidegger, C., Xie, Y., & Dervieux, C. (2022). Quarto (Version 0.3) [Computer software]. https://doi.org/10.5281/zenodo.5960048

This website is a copy of the [lab manual for the Fay Lab](https://thefaylab.github.io/lab-manual/) at the University of Massachusetts Dartmouth School for Marine Science and Technology thanks to their group's participation in the [Openscapes Champions program](https://openscapes.org).


