# Introduction {#intro}

We do rigorous quantitative science to support decision-making for living marine resource management. We conduct our work using Open Data Science principles, emphasizing scientific excellence (not perfection) that is transparent, reproducible, collaborative, and ethical. We aim to make our methods and results available and support ongoing learning.  
Our quantitative work is based on statistical thinking, using evidence-based approaches to compare among alternatives for models and management options.  

See the next chapter for more detail on our lab culture and philosophy. We are motivated heavily by the following two papers - which provide a blueprint for how we think about the way we do our work.  

[Lowndes, J.S.S., Best, B.D., Scarborough, C., Afflerbach, J.C., Frazier, M.R., O’Hara, C.C., Jiang, N. and Halpern, B.S., 2017. Our path to better science in less time using open data science tools. Nature ecology & evolution, 1(6), pp.1-7.](https://www.nature.com/articles/s41559-017-0160)

[Wilson, G., Bryan, J., Cranston, K., Kitzes, J., Nederbragt, L. and Teal, T.K., 2017. Good enough practices in scientific computing. PLoS computational biology, 13(6), p.e1005510.]( https://doi.org/10.1371/journal.pcbi.1005510)


[To come: recommended reading list]

## How we meet

Currently, we meet virtually by Zoom for weekly lab meetings, individual meetings with Gavin, and our Shut Up and Write session. 

## How we give feedback

Feedback, both giving and receiving it, is an important aspect of our lab. Most of the feedback we give and receive is when giving and attending practice talks. We expect feedback to be supportive but constructive. 

This [resource from UBC](https://scwrl.ubc.ca/student-resources/learning-strategies-for-communicating-science/how-to-give-and-receive-effective-feedback/) does a really great job of outlining the main points of how to give and receive feedback. 

## How we share things (and send them to Gavin)

To come.