---
bibliography: references.bib
---

# The importance of RDM {#importance}
Estimated time: 70 minutes

During this module we will share different perspectives and let you discuss with each other about the importance of RDM in ensuring research reproducibility. 
At the end of this module you should be able to:

*	Recognize the importance of research data management
*	Explain why RDM is relevant for reproducibility and re-use of data

## Activities 
*	Watch the Presentation (**before class 1**) - Why is RDM important? 
* Read Markowetz 2015: Five selfish reasons to work reproducibly OR [Watch the presentation](https://youtu.be/1Y_oIjlH-yg?t=355) (50 min) **before class 1**
* Set up a GitHub account (see [Assignment 1](https://estherplomp.github.io/TNW-RDM-101/03-Assignment-GitHub-1.html)) **before class 1**


## Why care about RDM?
Watch the presentation about the importance of RDM and hear what other researchers have as their worst nightmare. Why should you be aware of your Research Data Management?  

* [01-1_Module-1_Video_Presentation_Why RDM is relevant for you_Part1](https://surfdrive.surf.nl/files/index.php/s/eYiDxb1CP5E44Hh) (3 minutes, audio will play automatically in full presentation modus) - Data horror stories 
* [01-2_Module-1_Video_Presentation_Why RDM is relevant for you_Part2](https://surfdrive.surf.nl/files/index.php/s/JX7Oyns3vGCdDZ8) (5 minutes) - Benefits of managing and sharing data

Reflect about what you heard on the video and bring your thoughts and your horror stories to **class 1**.

## References
Markowetz, F. Five selfish reasons to work reproducibly. Genome Biol 16, 274 (2015). https://doi.org/10.1186/s13059-015-0850-7



