# Lab culture and philosophy {#culture}

We approach our science with a common denominator of kindness. As part of our core lab culture, we:  

* __Ask for help, and share our learning__
* __Make ourselves available__
* __Come prepared and engage__ 
* __Celebrate accomplishments (ours & those of others)__
* __Sustain a positive, safe learning environment__
* __Have an interdisciplinary (open) mindset__ 
* __Are mindful of our own biases__
* __Plan with intention, and follow through__
* __Foster inclusivity within our group and greater community__
* __Promote and sustain healthy work-life integration__
* __Practice radical candor__
* __Acknowledge and give credit to other lab member’s work__ 

Though we do not expect incoming members to memorize everything, we do expect members to be aware of the group’s values.  

**Ask for help, and share your learning:** We are all learners, and most of our learning is done from each other. It is inefficient to struggle through problems alone. Ask for and give assistance with appropriate cognizance of the value of your time and the time of the person you are asking. You are not the first or last person to encounter a problem. Whether it’s about code, clarifying a travel policy, or an edit to the Lab website, we encourage you to make your learning experience accessible to everybody else too, which means sharing what you’re struggling with. When you identify a problem, add an [issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue) to the [lab issues repository](https://github.com/thefaylab/lab-manual/issues) and update it with solutions when it is resolved. Also consider writing a tutorial/blog post for inclusion in our [lab’s shared resources](https://github.com/thefaylab/labhub), and sharing with the larger community by leading a lab meeting or running a workshop (QuantFish, woRkshop group, SouthCoast useR group, etc). 

**Make yourself available:** Be responsive to communication, and make time for things that address longer term goals, even when busy. For example, do not skip on things like attending seminars just because you have a big deadline looming (see note below on planning and organization). Note that being available does not mean that you are available 24/7 - this is not expected. We include regular opportunities to reorganize our priorities and plan accordingly, and shared time can be valuable for both group and individual goals. We value the role of collaboration and interaction in improving our work, so in-person availability for some time during normal business hours is expected (see section on attendance expectations).   

**Come prepared and be engaged:** Value your time. Be present during lab and individual meetings, and come ready to work. Contribute and participate in planning and lab discussions with curiosity, and without distractions. When it is your turn to run a meeting, come with an agenda and be prepared with questions. Aim to view meetings as a contribution to your work and productivity.  

**Celebrate accomplishments (yours & others):** You and your colleagues work hard. Things don’t always go exactly as you plan. Be supportive and proud of yourself and your peers when you accomplish things. We are not competing with each other - someone else’s success does not mean your failure. Share your accomplishments with others, and highlight the successes of your peers too! We want to know when you present at events big and small, make progress on academic goals, do good things in your community, and even when you take cool bird pics.  

**Sustain a positive, safe learning environment:** Everyone learns something for the first time at some time. Expressing that you don’t know something or how to approach learning about it is OK, and we understand that this can make someone feel vulnerable. We strive to maintain a culture that allows for and encourages this vulnerability. Community members should not be disparaged for not knowing things, and in addition, should not be disparaged for knowing things or wanting to learn. If you want to do something but can’t do it yet, ask for help!  

**Have an interdisciplinary (open) mindset:** We apply our work at the science-policy interface. This means we work on problems that span multiple disciplines. Co-creation of knowledge requires approaches that can result in solutions that would not be possible with siloing. You will be collaborating with others who have different types of expertise, values, and terminology. Trust the expertise of others and actively seek feedback, recognizing the importance of specialization. This also means that when we communicate science, we acknowledge the people and perspectives that have produced that knowledge.     

**Be mindful and aware of your own biases:** We all have biases that are inherent and can not be removed, but we can still work on both being less biased, and more aware of bias in ourselves and others. Periodically [check in on your biases](https://medium.com/better-humans/cognitive-bias-cheat-sheet-55a472476b18).  

**Plan with intention, and follow through:** Be organized and adaptable. Things don’t always go as planned and that’s OK. Planning can help you adapt when they don’t (see Come Prepared). Find a program/project management approach that works for you (see “How we work”); being organized and prioritizing tasks can reduce stress and help you progress with your goals. Blocking calendar time, coworking, or having an accountability buddy are good tools to help you stay focused and set aside time to follow through with responsibilities.  

**Foster inclusivity within our group and greater community:** Part of our lab culture is that we are good citizens of our community, we take on leadership roles within SMAST and the University, we are supportive of others in our community during their milestones, we actively participate in SMAST events (e.g. the Intercampus Marine Science (IMS) graduate research symposium) and engage with others in our work. We aim to be good neighbors who contribute meaningfully to the places we work, live, and frequent. Work with Gavin when crafting your individual mentoring/development plans (see Chapter on Onboarding) to identify where to focus your efforts.  

**Promote and sustain healthy work-life integration:** Our scientific research is not the only important thing in our lives, and publishing research is not the only mechanism by which to provide science and support to our communities. We recognize the importance of our other commitments in keeping us mentally and physically healthy and allowing us to bring our whole selves to our efforts. Try not to normalize overwork or being busy as achievement or status. Do normalize spending time doing things that bring you joy outside of work and sharing these aspects of our humanity with each other.  

**Practice radical candor:** We [care personally while also challenging directly](https://www.radicalcandor.com/). Be honest when communicating, accept critical (but kind) feedback, and give the same to others. We are here to work together, so if there are better ways we can do that then we communicate it and establish boundaries, and when we receive kindly delivered feedback, we genuinely consider and respond to it, without taking it personally. 

**Acknowledge and give credit:** Working as part of a team, we will often (always) be building on work done by others, receiving assistance with work (see “Ask for help”), and using others’ words, code, content. In the spirit of accessible, applicable, and reproducible science, we acknowledge and give credit for those contributions, in all forms of communication. We share content and code within the group with this expectation, honoring the collective responsibility of acknowledging the work of others, as this is what allows us to share freely. Some easy approaches include adding hyperlinks to the work of others or their social media in your work, including names and photos of your collaborators in presentations, and thanking them directly if they’re in the audience. This also helps to amplify their voice and work as well as yours. 

