# Expectations {#expectations}

In addition to agreeing to follow our communities codes of conduct and the university academic integrity policy, we expect everyone in the group to echo our lab culture (Chapter \@ref(culture)). 

__Individual mentoring plans:__  Gavin will work with each of you to develop your individual mentoring plan that serves to ensure your time in the Fay lab progresses your short, medium, and long-term goals. This is a useful planning document that assists in aligning expectations. Graduate students will revisit the mentoring plan during an individual meeting with Gavin at the beginning of each semester & the start of summer. Other lab members will revisit these at appropriate time scales (e.g. every 6 months).  
A template for these, with thanks to [`@duffy_ma`](https://twitter.com/duffy_ma) can be found [here](https://docs.google.com/document/d/1ie3nc6iqW5cWit_MV8BUIVmREbvUZ8b0P9dR8CGgleQ/edit?usp=sharing).

In addition, it is useful to have broad (for all lab members) and specific (i.e., grad students, research staff, etc.) expectations of our roles clarified. These are outlined below.  

## Working hours

Gavin generally does not hold people to working a fixed schedule, or to be in the office for a certain schedule. As adults, we should all set the working schedule that is the right fit for us, and it is likely that what this 'fit' is will change over the course of the time you are in the lab. Depending on the nature of your appointment, there may be specific hours that will need to be worked and you should work with your main collaborator to outline these.  

Gavin generally does not work evenings or on weekends, and does not expect that people in the lab are available at these times. Lab members should also not expect others to be available during these times.   

Graduate students are generally funded on annual research assistantship (RA) stipends. The RA contracts state that this stipend is for 20 hrs of work per week during the academic year and 40 hrs per week during summer to support full time study in the academic program. Most usually, students on RAships are being paid from a research grant where the focus of the grant is the topic the student is working on for their thesis research, so there is overlap here. We believe that training to do the research is part of the job, so this would include courses and additional time to read/learn methods, software too. Some people find that counting 'billable hours' is productive for them as it helps them keep accountable to themselves. Others do not find this method useful. Regularly assess what works best for you.  

Full time is enough, and we do not expect team members to work nights and weekends, though do not enforce a particular working hours schedule because students should feel flexible enough to create a work schedule that works for them. Lab members should not expect others to be available during evenings and weekends. There is value to interacting with others as part of your work, and we do expect you will be available during normal working hours for at least some of the time during the week. We also recognize that there will occasionally be times where there is a need to work more to meet a deadline, but this should be the exception - an expectation of overwork is not to be normalized.  


## Email

In the lab, we communicate via email. You should therefore check your email at least once a day during the normal work week. We also make use of Google Docs and issues on GitHub to record institutional knowledge and hold conversations regarding research tasks. Note that being available does not mean that you are available 24/7 - this is not expected. Do not expect responses to emails after regular business hours on weekdays, or on weekends. However, because we recognize that lab members should be able to create a working schedule that is right for them, lab members should not be penalized for sending communication during these times.   


## Attendance at regularly scheduled events

Attendance is expected at:
* Departmental seminars  
* Weekly lab meetings / quantfish woRkshops  
* Individual meetings with Gavin to discuss and work on your research  
* SMAST thesis and proposal defenses  
* SMAST all hands meetings / start-and-end of semester events  
* Annual UMass Intercampus Marine Science graduate research symposium


## Outreach

We share our learning and time with others beyond our lab, knowing that this builds community and ultimately improves both the quality and impact of our science. This doesn’t mean individuals do everything, however. We take on leadership roles within SMAST and the university, are supportive of others in our community during their milestones, actively participate in SMAST events (e.g. the IMS graduate research symposium), and perform outreach. Ask others in the lab about activities they are part of, and work with Gavin when crafting your mentoring plan to identify outreach strategy that meshes well with your goals.  


## Expectations for the PI

Gavin (as PI) will (at a minimum) provide:  
* Technical support for analysis (e.g., access to computing, training on techniques)  
* Positive feedback & constructive criticism on work  
* Professional career support  
* Support for non-technical aspects of making career progress  
* Regular meetings (every two weeks) to discuss work & maintain progress on goals  
* Provide clear and honest appraisal of your funding situation  


##  Graduate students

You are responsible for your degree. This means you need to stay on top of program and university deadlines, requirements, etc. See Chapter \@ref(umassd-resources) & Chapter \@ref(smast-resources) for links to resources.   

Before registering for each semester, you are required to meet with your advisor (Gavin) to review your tracking sheet (SMAST academic milestone document) and discuss plans for the forthcoming semester (classes, activities, etc.).  

Course of study: Work with Gavin when crafting and revisiting your individual mentoring plans to identify classes that you will take during your academic program. Look beyond those offered at SMAST to include elsewhere at UMassD, the UMass system, and also at other institutions (consider the value of a semester exchange). A list of classes that lab members have taken, and suggested course of study schedule for Fay lab grad students can be found in Chapter \@ref(courses).  

We schedule regular individual meetings with Gavin throughout the year. At a minimum during the semester these will take place every two weeks, although there may be times when more regular meetings are needed. Meetings are a chance for you to get focused time with Gavin to discuss and work on your research. Thus they are your time, not Gavin’s. Come with an agenda with a list of things that you want to accomplish and work on during that time.   

We share our research at local, national, and international meetings, and publish our findings in the scientific literature. Gavin strives to provide financial support for grad students to attend at least one major conference per year. You should expect to give a presentation (a poster or a talk) on your work at these.  

### Funding {#exp-funding}

Gavin does not typically accept students into the lab without being able to guarantee at least 2 years of full funding. Students are encouraged to seek and apply for extramural funding to support their work. This includes scholarships and fellowships to pay for salary, but also smaller grants for travel, workshop attendance, or research costs. There are many opportunities out there, particularly for students. Some resources are outlined in Chapter \@ref(funding).  


## Undergraduate students

You will most likely be working with one of the lab’s research team as your primary research supervisor. The grad student or postdoc you are working with on your project will be your primary source of contact and you should work with them to establish and define your work schedule, protocols for your work, and to ensure you have the necessary equipment to perform your work tasks.  

Although the grad student / postdoc is your primary contact, always feel like you can reach out to both [Gavin](mailto:gfay@umassd.edu) as lab PI and [Ashleigh](mailto:anovak@umassd.edu) as lab manager. We are excited to help you use your position in the lab to further your career goals and want to work with you to help you achieve them.  

If you are an hourly worker (either federal work study or grant supported) then it is critical that you complete your timesheets through HR Direct with your hours worked, so that you can get paid. Please submit your electronic timesheet each week by noon on Friday, to allow time for Gavin to approve. Alert your research supervisor AND Gavin as soon as possible if there are any complications with regard to pay. We want you to be compensated for your work in a timely fashion.  


## Postdoctoral researchers

Postdocs are independent researchers and likely will have significant collaboration with researchers at other institutions as part of their research and position. Postdocs in the lab may also be sharing time between SMAST and another opportunity.  

In general, postdocs are expected to:  
* Be present and involved in lab meetings, workshops, campus seminars, and conferences.  
* Provide mentorship, technical support, and assistance to other lab members  
* Communicate both successes and sticking points on a regular basis with the PI  
* Work independently and collaboratively  
* Participate in professional development opportunities  
* Lead and assist in designated research projects  
* Develop and submit proposals to fund future research  

On day 1 of his postdoc at NOAA NEFSC, Gavin's postdoc advisor said "Your first job is to look for your next job". While a postdoctoral position is a scienctific research position, it is also a training opportunity and a step to something else, and a full-time permanent position beats a postdoc. Do not feel bad or awkward about pursuing (and taking) employment opportuntities, and also training opportunities that help you move toward that next step. We want you to succeed!  

[As benefited employees at UMass Dartmouth, postdocs are able to enroll in a limited amount of graduate coursework as part of their benefits package. Talk with Gavin about this.]

Postdocs will likely have active roles on advisory working groups or other professional service roles. If opportunities are not immediately apparent through your funded research, then Gavin can help strategize about where is a useful space to target your involvement.    


## Research staff

Much like post-docs, research staff operate as independent and collaborative researchers on assigned projects. As these positions are often working directly alongside your mentor/direct collaborator on particular lab projects, meetings may be more frequent than those with others in the lab. Weekly meetings should have clear agendas, and can often be used as collaborative working time to make progress on specific tasks. 

In general, staff are expected to:

* Be present and involved in lab meetings, workshops, campus seminars, and conferences  
* Provide technical support and assistance to other lab members
* Communicate both successes and sticking points on a regular basis with PI
* Work independently and collaboratively
* Lead and assist in designated research projects
* Participate in professional development opportunities (i.e., workshops, conferences, submitting previous position manuscripts [without detracting from new position])
* Seek and pursue new funding opportunities when appropriate (this will likely be dependent on your timeline)
* Produce expected output from assigned grants
* Be flexible! Additional projects may be assigned to give additional funding for your position  
* Serve as a role model and go-to resource for other members of the lab

Research staff positions may be somewhat flexible in scope. For example, the position may include some lab management, leadership, and communication responsibilities. Exact set of responsibilities and duties will be clearly defined in your position description and expectations agreed on in your work plan.  


