# Funding {#funding}

Gavin does not typically accept students into the lab without being able to guarantee at least 2 years of full funding. 

Funded position openings in the lab will be posted through the lab website, twitter account, and via other distribution feeds (e.g. EcoLog).  

Gavin encourages all students to apply for external funding through graduate scholarships. Some relevant ones include the NMFS-Sea Grant Graduate Fellowships in Population and Ecosystem Dynamics, NSF Graduate Research Fellowship Program, Ford Foundation, NOAA Nancy Foster scholarships, and Margaret A. Davidsonn Graduate Fellowships, though there are many other opportunities (more provided in the link below).  

Here is Gavin's living document of recurring funding opporunities [Google Doc](https://docs.google.com/spreadsheets/d/1YGtSWJj2socIGtHLbBpHmJ7rPeDiECsdjgIz8FxUYMA/edit?ts=5e289f99#gid=0). Gavin not only encourages students to obtain additional funding, but also staff and post-docs. And for all to apply for travel grants when attending conferences, where applicable. 

This resource is updated fairly regularly, and largely contains resources to fund yourself/research. It includes the opportunity name, institituion, link, grad/undergrad/postdoc/all/early career/etc designation, the deadline, and important notes. 

Gavin will also share funding opportunites as they come up, either to the group or in individual meetings.  

