# Communication {#communication}

Acknowledge communication and engage with others about your work. This includes communication with the lab team, your peers, collaborators, and also communicating your work to others.
If someone works on something for you or provides you with feedback on your work, thank them and engage with them on their feedback. Our science improves by engaging with conversations about your work. View such interactions as opportunities to be collaborative rather than evaluative. Chances are if someone asks you questions about your work it is because they are interested in your science.   
Acknowledging communication and thanking others for their work is part of the profession, and it also helps collaboration by continuing conversation.  
While our philosophy applies, in that you shouldn't feel like you have to be on email all the time, don't let you email inbox become a black hole where questions / thoughts  get sucked into and no response emerges.  

We also believe in being intentional in communicating our work. While publishing and conference presentations are thought of as the standard forms in which science is disseminated, there are a number of ways in which you can communicate your work with others, depending on your audiences and chosen levels of engagement. You should always invest in these at the level that is of interest to you. Here are some things we recommend as members of our team.  

## Inclusive science communication

This [Google Doc resource](https://docs.google.com/document/d/1g7uXZzsC1QBCZWz4cRsERyzf6CrLKVXyLM_MTqvxK4A/edit?amp;urp=gmail_link) created and curated by Dr. Sunshine Menezes, the ED of the Metcalf Institute at URI, covers a wide range of topics related to inclusive science communication, education, and public engagement with STEM topics. We suggest you take a look!

## Curriculum Vitae

Keep your CV up to date. We share our CVs within the group in [this Google Drive folder](https://drive.google.com/drive/folders/1_VDBjhUkH4Tx4IeUTPKsmQueFKEhQi4f), both to give each other ideas about what to include, but also having these in one place makes it easier for Gavin and others to reference information from them when needed.  

[Here is a link to a lab-chat issue on CV building based on a 05/05/2020 lab meeting.](https://github.com/thefaylab/lab-chat/issues/10)


### Google Scholar profiles
Having a Google Scholar profile is a very easy way to curate your web presence and have a place where people can find you and your published papers and reports.  
We recommend everyone sets up a Google Scholar profile as soon as they have a paper or technical report. It takes about 5-10 minutes to set up, and one advantage is that Google Scholar self-updates and will add your papers and citations as you publish and people use your work. This is a really easy step to creating a web presence without having to set up a website.


## Personal Websites

**Why have your own website?**

1. People will Google you. They might as well see what you want them to.
2. Give people an easy way to find you and your work.

One way to do this is a personal website. This doesn't have to be extensive, but can be a good way to curate your web presence.  

There are heaps of tools out there to create and publish websites. Our recommendation is to choose something that it is easy to update, and fun / interesting for you to use. Many options are free.  
Some options for creating sites include: GoogleSites, Weebly, Squarespace, WordPress, R Markdown, GitHub.  

**What should you include?**

Ultimately this is up to you and how you would like to present yourself and your work. But some common things you could include are:
*not an exhaustive list*

- BioSketch
- Research interests/overview
- Projects
- Publications
- CV
- Blog posts
- Contact info

An example website (though many amazing others exist and you should check those out): [Ashleigh’s webpage using the free version of Weebly](https://ashleighnovak.weebly.com/)

## Twitter

Twitter is a great tool for interacting with others about your science. It is also a great platform for learning about new research and papers, finding out about jobs and fellowships, learning and discussing methods, discussing topics about how we do science, professional development, mental health and expectations around science and graduate school, and is a great venue for bringing ones whole self to the science. etc. Most of us have our own personal Twitter accounts and use them to varying degress. Everyone in the lab can post to the lab Twitter account too. Ask Ashleigh if you are interested in doing a takeover of thefaylab account for a week (which could also be a chance to dip your toe in to Twitter if you don't use it).  

[link to paper on use of twitter for rstats!]

## Social Media

[Link to papers on social media in fisheries ]

As you know, there are many social media platforms, and many (all?) of these are being used in some way for science communication. This includes but not limited to: 

- Twitter
- Instagram
- Facebook
- LinkedIn
- TikTok
- Youtube
- Researchgate

All have a different purpose and type of engagement. Think deliberately about how (and if) you want to use these tools. Using social media as part of your science communication portfolio can be useful and is popular, but it is not a requirement to be a successful scientist.  


## Contributing to regional publications  

[more to come on engaging with our local press, etc.]
