---
bibliography: references.bib
---

# Realising FAIR: Data Documentation {#realisingFAIR2}


In this module, we will focus on the realisation of FAIR data. 
We will explore some best practices and tools that can facilitate the implementation of the FAIR principles. 
At the end of this module you should be able to:
*	Recognize the relevance of documentation and be familiar with diverse tools to document data
*	Identify relevant tools to advance towards FAIR data 

## Activities 
*	Watch the videos about ‘Data Documentation tools’ and complete the corresponding quizzes.
* Write a readme file and share it on GitHub. Comment on another person's readme and provide them with some tips to improve. 

## Documentation tools 

Now that you know more about how to organise your data and name your files, we can talk about documentation. 
Documentation is vital to making your work understandable, which is, in turn, necessary for your work to be reusable.
Documentation is important not only for data, but for your projects in general, including the code you write. 
Your documentation should provide context for your project and its data and should, for example, provide information about the data collection, structure, and ownership.

In the next video we will talk about different methods and tools you can use to document projects, datasets, and code. We will also briefly talk about metadata.
 04-2_Module-4_Video_Presentation_DataDocumentation]
 
 ## Assignment: Create a ReadMe file 
 Estimated time: 15 minutes

1. Download the [Cornell template for a ReadMe file](https://cornell.app.box.com/v/ReadmeTemplate). 
2. Adapt and start filling in the template to describe a dataset of your project (you are allowed to delete and add new fields)
3. If you are unsure about the meaning of a component of the ReadMe file, go to: [Guide to writing "ReadMe" style metadata - Cornell University](https://data.research.cornell.edu/content/readme#best_practices)
4. When you're finished, share your template on GitHub. 
5. Pick a ReadMe file of someone else and read it. 
Provide feedback on the clarity of the ReadMe. 

## Assignment: Data Dictionaries (for tabular data - optional)
 Estimated time: 15 minutes
1. Watch a [video on data dictionaries](https://www.youtube.com/watch?v=Fe3i9qyqPjo)
2. Go to a tabular dataset you are working on or have worked on.
3. In an excel spreadsheet, start creating your data dictionary. 
Ave the data dictionary in the same folder as the dataset you're describing.
List all the variables that you find in the dataset on column A. 
Then, add a clear and understandable description of that variable on column B.

Note that you can also [create a package for your data with Frictionless Data](https://create.frictionlessdata.io)

## Assignment: Electronic Lab Notebooks (optional)
Estimated time: 20 minutes
[TU Delft offers two different Electronic Lab Notebooks](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-note
book), eLABjournal and Rspace. 
Watch the short videos introducing them:
* [eLABjournal intro](https://www.youtube.com/watch?v=ys4BKEWWnEc&feature=youtu.be) (4:11 minutes):
* [RSpace intro](https://www.youtube.com/watch?v=q2CEnZRC1_o&t=5s) (1:43 minutes):

Try out one of the Electronic Lab Notebooks: 
* [RSpace](https://rspace.tudelft.nl) 

Answer the following questions to see if the Electronic Lab Notebooks are helpful to your work: 
- Was there any specific feature in one or both of the ELNs that would be particularly useful?
- What are the pros and cons that you can already think of when using an ELN for documenting your lab work?



## Resources
*	Cornell University Research Data Management Service Group. Guide to writing “readme” style metadata. URL: https://data.research.cornell.edu/content/readme
*	Alderliesten, René; Yao, L. (Liaojun) (2017): Mode I fatigue delamination growth in composite laminates with fibre bridging. 4TU.ResearchData. Dataset. https://doi.org/10.4121/uuid:6da548f6-f801-41b4-8d88-db9ae81f6913
*	JupyterLab. Demo: The Lorenz Differential Equations. URL: https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo
*	Frictionless Data. Data Package Creator. URL: https://create.frictionlessdata.io/
*	Software Heritage. CodeMeta generator. URL: https://codemeta.github.io/codemeta-generator/
* [Electronic Lab Notebooks at TU Delft](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook)
*	[FAIRsharing.org](https://fairsharing.org/): standards, databases, policies. 

### Quiz Data Documentation tools
Test your knowledge after watching the ‘Data Documentation tools’ video. Indicate if the following sentences are True or False.
1.	Metadata - data about data - is an important type of documentation (Answer: True)
2.	README files can be used only to document whole projects (Answer: False)
3.	Codebooks are used for the documentation of code (Answer: - False)
4.	GitHub/GitLab and Jupyter notebooks are good tools for documenting code (Answer: True)
5.	Metadata can be added to data as part of the file name, using a README file and using tags (Answer: True)