# Academics {#academics}

This chapter (for now) contains information pertaining to lab graduate students enrolled in the Intercampus Marine Science (IMS) program.  

You are responsible for your degree. This means you need to stay on top of program and university deadlines, requirements, etc. See Chapter \@ref(umassd-resources) & Chapter \@ref(umassd-resources) for links to resources.   

The [IMS policy](https://my.umassd.edu/html/terminalfour/media/umassdartmouth/smast/lab-pdf-files/IMS-General-Policy.pdf) should be the first port of call for information about program requirements, and what needs to be done when.  

Registration: Academic credit registration management at UMassD is done through COIN. Registration for each semester takes place about mid-way through the previous semester (see the university academic calendar for dates). It is critical to register promptly to facilitate faculty and institutional planning (and avoid late registration fees). Before registering for each semester, you will meet with Gavin to review your tracking sheet (SMAST academic milestone document) and discuss registration plans for the forthcoming semester (courses and/or research credits, continuation).  

See Chapter \@ref(courses) for details of courses available to IMS graduate students.  
Course of study should be selected with the program requirements in mind - as always, refer to the [Intercampus Marine Science Program Manual](https://my.umassd.edu/html/terminalfour/media/umassdartmouth/smast/lab-pdf-files/IMS-General-Policy.pdf) for details.  
  
Most students take many of their core program requirements in the first year. An exception may be PhD students who save one of the Oceanography requirements for the 2nd year, depending on other courses being offered.  

Thesis credits: These are required for both MS (thesis-based) and PhD degrees. For the PhD, research credits take the form of pre-dissertation credits if completed before advancing to candidacy. Pre-dissertation research credits taken during the semester in which a student completes their comprehensive exams (i.e. passes their proposal defense) can be converted after the fact to dissertation credits. Once thesis and dissertation credit requirements have been met, MS and PhD students will often maintain registration through 'continuation of program' credit, where no credits are earned but enrollment status is maintained.  

[UMassD student thesis templates and guidance](https://www.umassd.edu/graduate/student-resources/)

[Chang Liu's LaTeX thesis templates](https://github.com/cliu3/SMAST-Thesis-Template)

## MS students

Thesis Proposal: MS students in the Fay lab prepare a thesis proposal during their first year to identify and refine their thesis research topic ideas and outline methods that will be used to address the research questions. The proposal also serves as a guiding document for your initial committee meeting(s). Scope and plans for the MS thesis research will be developed through your meetings with Gavin and with the project team (for students whose work is being funded by a research grant). Your thesis proposal should contain a literature review, identification of research questions, an overview of the methods that will be used, and description of expected results and relevance/significance of the research. Aim for the proposal to be about 8 pages of text. While not a formal requirement for the IMS program, a MS thesis proposal serves to clarify and outline expectations for the degree for both the student and the thesis committee, and serves as a blueprint for building out the thesis itself (indeed you may likely re-use some of the text later). Thesis proposals written by other lab members are good examples of how these documents can be structured. 

Thesis Committee: 
Forming  your thesis committee: Your MS thesis committee serves as your guidance team during your research, and should be viewed as colleagues and collaborators. While building your proposal, discuss with Gavin who should be on the committee. Three committee members is the usual size, though sometimes students will have a fourth member. Generally in our program a committee will be made up of your advisor (Gavin), an additional UMassD faculty member, and an external member (often an agency collaborator on the project, e.g. at NOAA NMFS). See the official university guidelines for more specifics [link here]. 

MS Thesis: [guidance on thesis structure to come]

Remember, not everything will go to plan and your interests and findings may change. Content of theis proposals is not set in stone and can always be revised with communication and collaboration with the committee. View proposals as items that help you build your scientific products rather than evaluative procedures that need to be checked off.  

## Ph.D. students  

PhD dissertations in the Fay lab tend to comprise chapters that will form ~4 publications. Gavin encourages students to think about dissertation chapters as publishable units. In the disseration, these 4 chapters will be accompanied by a general Introduction, and a concluding Synthesis chapter that ties the work presented in the dissertation together under the overarching research theme and goals.  

Milestones

### Pre-proposal _(or "Preposal", copyright M. Winton)_
PhD students in the Fay lab prepare a pre-proposal during their first year to outline the overall goals and themes of the dissertation research topic, and identify the individual research chapter topic questions. The pre-proposal serves as a guiding document and conversation starter for your initial committee meeting. Scope and plans for the  thesis research will be developed through your meetings with Gavin and with the project team (for students whose work is being funded by a research grant). Your pre-proposal should contain a literature review, identification of research questions and potential chapter units, an overview of the methods that will be used to address the research questions, proposed course of study (coursework, etc.), and relevance/significance of the research. Aim for the pre-proposal to be about 5 pages of text. A 2-page precis version is useful when initially talking with committee members. While not a formal requirement for the IMS program, a pre-proposal serves to clarify student interests and goals for the degree for both the student and the thesis committee, and serves as a blueprint for building out the preliminary work and the dissertation proposal (indeed you may likely re-use some of the text later).  

### Dissertation Committee

Your PhD thesis committee serves as your guidance team during your research, and should be viewed as colleagues and collaborators. There is a required minimum for interaction with the committee, but you should add to this. After you have formed the committee, it is advisable to hold a committee meeting at least once a year, but it is encouraged to continuingly interact with committee members.  
While building your pre-proposal, discuss with Gavin who should be on the committee. For PhD committees, four members is the usual size, though often students will have a fifth member. Generally in our program a committee will be made up of your advisor (Gavin), two additional UMassD faculty members, and 1-2 external members (e.g. agency collaborators on the project funding the research, e.g. collaborators at NOAA NMFS). Aim to hold your first committee meeting no later than during the 3rd semester of your program. See the official university guidelines for more specifics [link here].

[something on what is expected at committee meetings, e.g. presentation]

### Comprehensive Exams

As detailed in the IMS policy, PhD students undertake a two-part comprehensive examination, a 2-day written exam, and a public presentation and defense of the proposal. The written exam is taken once students have completed their coursework requirements (say after the 4th or before/during the 5th semester). Questions on the written exam include both open and closed book sections and will cover coursework and questions related to your field and dissertation topics. The proposal defense is usually scheduled the semester following successful completion of the written exam. Full requirement details for the exams are in the IMS policy. The comprehensive exam will be planned in coordination with Gavin, and the written exam requires 1 month preparation time (1 month of full-time work). See guidance below.
[Written exam format & guidance]
[Proposal defense format & guidance]

### Dissertation Proposal

A proposal describing the research that will comprise the dissertation is a required, formal part of the academic program. Proposals should describe the goals and themes of the research to be conducted, and its context within current state of knowledge. The proposal should outline the research questions that each chapter will address, and give a description of the methods that will be used in each. The proposal serves as a guiding document for the remainder of your program and is the document that you and your committee will use to agree on the scope of work to be completed to fulfill the degree requirements. Your thesis proposal should contain a literature review, identification of research questions, an overview of the methods that will be used for each of these, and description of expected results and relevance/significance of the research. Aim for the proposal to be about 15 pages of text. Detail of planning for each chapter will not be as comprehensive (it is expected that later chapters may not be as fleshed out), but the proposal should provide enough detail of what the student will do for the committee to evaluate whether the scope of work is sufficient (and likely make recommendations for reducing or refining this). It is common for students to have completed or be close to having completed work for at least one of the chapters by the time of defending the proposal.  
Ultimately, the proposal serves to clarify and outline expectations for the degree for both the student and the thesis committee, and serves as a blueprint for building out the thesis itself (indeed you will re-use some of the text later).  

PhD Thesis: [guidance on thesis structure to come]


Remember, not everything will go to plan and your interests and findings may change. Content of thesis proposals is not set in stone and can always be revised with communication and collaboration with the committee. View proposals and exams as items that help you build your scientific products rather than evaluative procedures that need to be checked off.  
