# Assignment - Create DMP {#DMP}

For this assignment, please create an account for DMPonline, and use the TU Delft template to create a plan for your project. 
In the following document, DMPonline user guide, you will find a clear step-by-step guide to complete this activity. We expect you to:

1. Create an account in DMPonline 
2. ‘Create a new plan’ for your project choosing ‘Delft University of Technology’ as the primary research organisation
and tick ‘No funder associated with this plan or my funder is not listed’ in the ‘primary funding organisation’
3. Fill in the ‘Project Details’ according to your project.
4. Go to ‘Write Plan’ 
5. Go back to your slides or papers and post-it’s of your data flow map of week 1 and 2 and use the information in there to fill in the questions of the data management plan. If appropriate, you can use the ‘Additional Information’ box in the template to add as many details as possible according to your data flow map.
6. If you don’t know how to answer any of the questions please let us know in [Issue ? on GitHub](link). 

## Discussion - Questions & Reflections about your DMP (mandatory)
Please share your questions and/or reflections that came up while filling in the DMP of your project. 
For example:

*	Were you able to answer all the questions on the DMP template using your Data Flow Map? 
*	If not, which sections were you not able to answer? What kind of additional information would you need?


