# Computing resources {#computing}

Because our work is quantitative, research computing skills are an important part of your toolset. Most of our team uses the open source software `R` for a lot of their workflow, though you probably want to also learn an additional tool during your time in the lab (for many, the natural choice here is `TMB` and/or `ADMB`, as these `C++` template languages are the basis for many statistical population dynamics models in fisheries stock assessment).  

Fortunuately, there are heaps of resources (including your labmates!) to help you with your learning.  


## Overview of Computing at UMassD
As a student of UMass Dartmouth, the Computing and Information Technology Services (CITS) provides access to essential resources and help when you need it. Information on how to set up your UMass login and access the UMassD portal can be found on the [New Students UMassD CITS webpage](https://www.umassd.edu/cits/newstudent/). A list of available programs and licensed software can be found on the [Software Licensing page](https://www.umassd.edu/cits/software/).

## SMAST computing facilities
Once you are set up with your UMass login, you will need to submit an SMAST IT Access Request Form to gain access to the SMAST Server. This form can be found under the SMAST Occupants page, Information Technology section through the UMassD portal. If you have additional questions or issues, you can email SMAST IT through [smastsupport@umassd.edu](mailto:smastsupport@umassd.edu). 

## Administrator Privileges
As your computer is your main piece of lab research equipment, it is important to be able to use it effectively. Please ensure you are familiar with procedures for and have the ability to make changes on your computer as an administrator.   

## Remote meetings via Zoom

UMassD uses Zoom as its conference call software solution. Everyone should activate their Zoom Pro account which is part of the university license.  Information on how to set this up can be found [here](https://instructionaldev.umassd.edu/zoom/). 

## Collaborative software

For writing, we collaborate using GoogleDocs. For code and analyses we encourage the use of version control (see Wilson et al. paper for what this could look like), stepping toward the use of git and github for sharing code and analyses. We believe there are many advantages of using these tools to help simplify workflows and shift cognitive load to the science being done rather than on organization and bookkeeping (which computers are good at). Recognizing that these tools represent a learning curve, we provide training in their use, and also encourage alternatives for sharing and documenting work. For example, code and analyses may also be shared among collaborators using a Google Drive folder.  

## Backups and set up to Lab storage server 

The average life expectancy of a hard drive is less than the duration of most graduate programs. Thus it is critical to ensure your data and work are backed up regularly. You may have personal backup solutions (e.g. through Dropbox, Google Drive, etc.) but the lab has dedicated storage space on a university server that is backed up in multiple locations. Your data should be backed up on here. For information on logging on and accessing this, 
see information provided on a [GitHub issue](https://github.com/thefaylab/lab-chat/issues/5)


## Introductory R learning resources {#learnr}

Welcome to `R`! There are so many learning resources out there it can feel a little overwhelming in terms of what to choose! To get you set up and started, [Happy Git and Github for the useR](https://happygitwithr.com/) is a great resource, and is created by the same authors as the now-legendary [stat545.com](stat545.com) course. Their resources are extremely comprehensive and they have a fantastic Intro R course, especially for those who will be using R for doing statistics.   

Right now, we REALLY like [this short intro course](https://rstudio-conf-2020.github.io/r-for-excel/) by [`@juliesquid`](https://twitter.com/juliesquid) & [`@allisonhorst`](https://twitter.com/allisonhorst). They teach a lot of the workflow and tools around using R right from the get go, which we think is more helpful than knowing how to do all the things. The (excellent) materials are thoughtfully put together, link to a ton of other great resources, and just like the online #rstats community in general, are super supportive of new learners. 

We also really like: 
* [Teacup Giraffes](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html) R and statistics materials from Desirée De Leon and Hasse Walum.   
* [Data Science in a Box](https://datasciencebox.org) course by Mine Çetinkaya-Rundel, and
* [Adventures in R](https://www.adventures-in-r.com/) by Kelly Bodwin.  

If you want a book to work from/through, [R for Data Science](r4ds.had.co.nz) is highly recommended.  (book is free online)  

The [R Studio Education](https://education.rstudio.com/) team have assembled a phenomenal array of courses, tutorials, and other materials for learning R, and for many types of data analyses and modeling using R. These are top notch and so thoughtfully put together. There is something for learners at all levels.  

A plug for the online R community. Follow the hashtag #rstats, & also check out accounts [`@RLadiesGlobal`](https://twitter.com/RLadiesGlobal) & [`@R4dsCommunity`](https://twitter.com/R4dsCommunity). The weekly #TidyTuesday social coding project is also a great way to practice your growing R skills. Have fun!  

The R4dsCommunity Slack is a briliant resource for getting help to your R questions and finding tutorials. They also hold online Office Hours where you can get help with R from a real human.  

The [RStudio Community](https://community.rstudio.com/) is a great go-to.  

Learn R from within R with interactive sessions using [swirlstats.com](swirlstats.com).  

The [carpentries R lessons](https://datacarpentry.org/R-ecology-lesson/) are also a fab resource.  


## TMB and ADMB
[resources detail]

