# UMass Dartmouth Resources {#umassd-resources}

## General information about UMass Dartmouth

Access SMAST's directory [here](https://www.umassd.edu/smast/about/directory/)...though doesn't get updated frequently.

### University Codes of Conduct
- [Student conduct and dispute resolution](https://www.umassd.edu/studentaffairs/departments/student-conduct-and-dispute-resolution/)
- [SMAST's code of conduct and diversity statement](https://www.umassd.edu/smast/about/). Note, link to a word document should be at the bottom of the linked webpage.

### For Grad Students:
- [Official SMAST webpage for current and incoming students](https://www.umassd.edu/smast/admissions--aid/current-students/). This has information on orientation materials, forms, scholarships/fellowships/assistantships, and academics.
- Though out of date, the __unofficial__ [SMAST graduate student page](http://www.smast.umassd.edu/grad_students/) is a good resource to know exists.

### For New Employees:
- New employee onboarding checklists and paperwork
  - Key card access -> see Mike Marino, Assistant Dea of Operations (SMAST)
  - New hire paperwork -> Refer to Leslie Mercure (main campus)
  - Benefits package questions -> Refer to Sandra Escaleira (main campus)
  - New hire goodie bag -> Cynthia Costa (SMAST)
  - Setting up your new laptop/desktop -> Andre Schmidt, Systems Administrator (SMAST)
      - Andre is useful in getting programs installed on your computer too. If you are staff, the Adobe suite (including Illustrator) is available. 
- Key contacts if you are a new hire: 
    - [Leslie Mercure: Recruitment Manager & Sandra Escaleira: Benefits Specialist](https://www.umassd.edu/hr/hr-team/)
- [Parking](https://www.umassd.edu/parking/) and transportation: Parking at SMAST is free and if you are a new hire (staff) then parking on Main Campus is also free. Go to the lower level of the campus center on Main Campus to get a parking decal. But there is short/temporary parking available on campus so you may feel it's not necessary to obtain a pass. It's up to you and your preferences!
