# SMAST Resources {#smast-resources}

There is some overlap between this page and Chapter \@ref(umassd-resources)
Link to UMassD Resouces chapter 

The SMAST [Department website](https://www.umassd.edu/smast/) lists all faculty, staff, and students across both departments (DEOS & DFO). This is not updated frequently but may help you in locating a specific person and their contact information.

[SMAST Directory](https://www.umassd.edu/smast/about/directory/)

If you need help with a specific task, there are some staff members that are more approproate to contact. Please use this link below to locate someone to help you. For example, if you are planning on traveling (DEOS & DFO), you see that Christine Fox is the primary contact with Sue Silva as the secondary point of contact. 

- [Staff at SMAST that are useful resources](https://github.com/AshleighNovak/Fay-Lab/blob/master/SMAST%20admin%20support%20matrix%20update_REVISED_11.29.18.xlsx) - click on view raw at bottom of page.
    - An excel spreadsheet which lists the primary and secondary points of contact for SMAST related business will be downloaded to your computer. 