# Assignment 5 - Data Flow Map reflection {#assignment6}

*Estimated time: 60 minutes*

Go back to your [Data Flow Map](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html) and reflect on your challenges, experiences and tips.

You will have to prepare and submit a slide before **class 2** about:

-   Which data flow map theme challenged you the most? And why?
-   What theme (from the data flow map) challenged you the least because you were already implementing RDM best practices before this course? (If any)
-   What RDM best practice have you already started implementing in your daily practice during the course?
-   If you haven't implemented anything yet, what will you get started with tomorrow after the course ends?

You will have 3 minutes to present your slide during **class 2** to your peers and they will have the chance to ask questions or exchange ideas!

Please **submit your slide to Esther before {{< var deadlines.assign5 >}}**

This assignment is based on @martinez-lavanchy2022

## References {-}
