# Wrap Up {#wrapup}

*Estimated time: 5 minutes*

In the past modules we focused on relevant topics concerning RDM. Starting with creating awareness about RDM, we have seen the essentials of RDM, the importance of FAIR data and how to create a planning for RDM. In this final module we give the opportunity to reflect on the course and share remaining questions.

At the end of this course you will be able to:

-   Realise the important role that good data management plays in research
-   Identify different types of research data and recognize the regulations, policies and/or legal requirements associated with them
-   List the main components of the FAIR data principles and connect them to your own research workflows
-   Employ the acquired knowledge to design an efficient research data management strategy for your project according to best practices

## Feedback

Please fill out [this Form](https://forms.office.com/e/8CAbUYbVmx).

## Other Courses

-   Check out the RDM website of the Library for an [overview of what other courses are available](https://www.tudelft.nl/en/library/research-data-management/)!
-   [Open Science MOOC: Sharing your research with the world](https://www.tudelft.nl/en/library/mooc-open-science-sharing-your-research-with-the-world)
-   [Open Life Science program](https://openlifesci.org/) which can be attended for 5 Discipline Specific Graduate School. For the course description and more details, see [intranet](https://intranet.tudelft.nl/-/open-life-science-programme).
